### ISSUE TITLE
Question about MySQL database

### ISSUE THREAD

**Issue by WhyANameWhy** [Chpetrou/EuroCoinCollection#2]
How to we add a database? Could you share a example database?

**Comment by Chpetrou** [comment]
You can add a **constants.php** file in the **include** directory containing the following code, replacing the word **placeholder** with the meaning of each respective comment:
```php
<? php

define('DB_USERNAME', 'placeholder');	// The database username
define('DB_PASSWORD', 'placeholder');	// The database password
define('DB_HOST', 'placeholder');	// The database host (i.e. localhost, if you are running it locally)
define('DB_NAME', 'placeholder');	// The database name (i.e. CoinCollection)
```

**Comment by WhyANameWhy** [comment]
I already did that but no tables for that database get created. It's always empty.

**Comment by Chpetrou** [comment]
I wrote this when I was in high school, which was a long time ago, and probably at that time I manually created and prefilled the database and tables.

So, you need to create four tables named, (**users**, **usercollection**, **countries**, **coins**) and follow the definition of each table written below.

> ### users
**id**: int _(auto increment)_
**email**: text
**password**: text _(should be saved as a hash)_

> ### usercollection
**id**: int _(auto increment)_
**coinid**: int
**username**: text
**year**: int _(4 chars)_

> ### countries
**id**: int _(auto increment)_
**iso**: text _(2 chars)_
**country**: text

> ### coins
**id**: int _(auto increment)_
**type**: text _(3 chars)_
**country**: text _(2 chars, equivalent to country iso)_
**coinname**: text
**imageloc**: text
**symbol**: text _(representing mint marks, etc.)_

Also, you could run only once the methods starting with **put** inside **dboperation.php** to prefill some tables, and use the other methods to help you get the information missing on the rest of the tables and fields.

**Comment by WhyANameWhy** [comment]
Thanks for everything.
